# Generated by Django 4.1.3 on 2023-03-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('complet', models.BooleanField(default=False)),
                ('creat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
